insert into batata (cosigo, pontuacao, num_rodadas, nome) values (1, 66, 41, 'Morissette Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (2, 7, 55, 'Buckridge Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (3, 64, 8, 'Grady and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (4, 43, 66, 'Larkin Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (5, 59, 16, 'Renner Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (6, 60, 73, 'Rosenbaum-Powlowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (7, 38, 79, 'Hilll-Mann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (8, 15, 97, 'McClure-Yundt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (9, 78, 63, 'Crist, Mayer and Beahan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (10, 43, 48, 'Lubowitz, Volkman and Strosin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (11, 95, 25, 'Aufderhar Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (12, 9, 13, 'Cormier-Crooks');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (13, 78, 74, 'Hahn, Fay and Hilpert');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (14, 64, 65, 'Satterfield, Rodriguez and Beer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (15, 48, 45, 'Jaskolski-O''Connell');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (16, 13, 9, 'King-Denesik');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (17, 23, 100, 'Wilderman Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (18, 58, 30, 'Cormier, Emmerich and Cormier');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (19, 21, 74, 'Altenwerth LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (20, 48, 68, 'Denesik LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (21, 66, 58, 'Strosin-Osinski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (22, 63, 15, 'Morissette-Padberg');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (23, 48, 62, 'Borer LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (24, 69, 32, 'Harber, Marquardt and Durgan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (25, 64, 69, 'Toy-Ziemann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (26, 47, 94, 'Gulgowski Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (27, 11, 75, 'Stokes-Osinski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (28, 53, 56, 'Medhurst, Luettgen and Hartmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (29, 14, 10, 'Jacobson LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (30, 18, 58, 'O''Connell Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (31, 30, 46, 'MacGyver, Hettinger and Ruecker');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (32, 45, 21, 'Moen Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (33, 93, 40, 'Kshlerin Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (34, 78, 20, 'Lakin LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (35, 25, 16, 'Koelpin-Kuhic');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (36, 35, 64, 'Powlowski, Yundt and Schoen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (37, 15, 60, 'Marvin, Harber and Marks');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (38, 26, 19, 'McKenzie, Luettgen and Zieme');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (39, 57, 53, 'Sanford Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (40, 20, 81, 'Herzog-Boyer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (41, 61, 47, 'Kozey-Friesen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (42, 55, 37, 'Hoppe, Wyman and Senger');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (43, 62, 53, 'Kautzer-Kuhn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (44, 70, 100, 'Labadie-Strosin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (45, 79, 91, 'Ward-Miller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (46, 14, 45, 'Bayer-Auer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (47, 14, 34, 'Rosenbaum-Halvorson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (48, 3, 38, 'Douglas Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (49, 80, 91, 'Grant-Pfeffer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (50, 81, 42, 'Brown, Kilback and Nicolas');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (51, 63, 81, 'Kulas, Bailey and Mills');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (52, 94, 62, 'Cole, Schroeder and Marks');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (53, 64, 98, 'Labadie, Carter and Feil');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (54, 64, 84, 'Yundt, O''Reilly and Satterfield');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (55, 10, 9, 'Hauck, Stamm and Kihn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (56, 69, 72, 'Nitzsche-Bahringer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (57, 29, 44, 'Satterfield LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (58, 77, 5, 'Sipes and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (59, 31, 46, 'Dietrich, Haley and Hayes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (60, 58, 73, 'White, Klocko and Will');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (61, 19, 86, 'Harber-Schuster');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (62, 21, 65, 'Hane, Bauch and Moen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (63, 39, 27, 'Carroll and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (64, 66, 46, 'Rice and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (65, 5, 20, 'Osinski-Powlowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (66, 59, 54, 'Casper Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (67, 63, 88, 'Treutel, Farrell and Hane');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (68, 33, 57, 'Lowe-Wilkinson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (69, 80, 32, 'Grimes-Cruickshank');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (70, 24, 85, 'McKenzie Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (71, 75, 24, 'Kuphal-Kihn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (72, 9, 21, 'Spinka, Goodwin and Pfannerstill');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (73, 88, 9, 'Cruickshank-Waelchi');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (74, 33, 27, 'Greenfelder LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (75, 40, 47, 'Swift-Ryan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (76, 40, 25, 'Erdman and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (77, 41, 70, 'Macejkovic-Brown');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (78, 14, 51, 'Kuhlman, Gorczany and Weissnat');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (79, 67, 31, 'Auer Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (80, 89, 50, 'Carroll, Donnelly and Hane');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (81, 64, 6, 'Senger, Cruickshank and Lind');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (82, 22, 16, 'Koch and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (83, 100, 59, 'Bahringer-Koepp');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (84, 97, 88, 'Wehner LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (85, 81, 83, 'Rowe and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (86, 2, 94, 'Schuster LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (87, 40, 62, 'Hauck, Heaney and Kulas');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (88, 71, 99, 'Abernathy Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (89, 100, 44, 'Kuhlman, Funk and Heller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (90, 86, 48, 'Bartoletti and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (91, 28, 77, 'Johnson, Turcotte and Boehm');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (92, 88, 78, 'Kerluke and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (93, 20, 18, 'Powlowski, Brown and Ullrich');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (94, 58, 14, 'Zemlak, Baumbach and Schmidt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (95, 59, 61, 'Schroeder-Hettinger');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (96, 3, 34, 'Ullrich-Batz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (97, 35, 95, 'Kirlin, Gutkowski and Metz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (98, 13, 98, 'Hagenes-Schaden');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (99, 22, 77, 'Bailey, Oberbrunner and Stehr');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (100, 51, 13, 'Hyatt, Goyette and Pfeffer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (101, 47, 54, 'Fahey, Lowe and Huel');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (102, 86, 81, 'Willms, Swaniawski and Hintz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (103, 75, 53, 'Homenick Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (104, 7, 83, 'Mraz-Cormier');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (105, 7, 25, 'Goyette LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (106, 82, 20, 'Nienow, Moen and Gutmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (107, 11, 24, 'Fisher and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (108, 7, 43, 'Rath-Dach');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (109, 40, 63, 'Pfeffer Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (110, 82, 75, 'Reilly, Wolf and Howell');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (111, 81, 29, 'Fahey Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (112, 47, 82, 'Bayer, Jacobson and Pfeffer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (113, 31, 90, 'Stark-Emmerich');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (114, 27, 39, 'Koch, Murazik and Nicolas');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (115, 83, 81, 'Auer-Veum');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (116, 29, 25, 'Kunde Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (117, 88, 70, 'Predovic Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (118, 91, 26, 'O''Connell-Schmeler');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (119, 63, 23, 'Beatty-Miller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (120, 82, 46, 'Hayes, Deckow and Kub');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (121, 40, 45, 'Prosacco Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (122, 17, 48, 'Conroy, Rolfson and Murazik');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (123, 16, 8, 'Gerlach-Wolf');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (124, 25, 94, 'Greenholt Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (125, 44, 33, 'Hartmann, Bauch and Feil');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (126, 96, 41, 'Maggio-Green');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (127, 45, 97, 'Schneider, Morissette and Ryan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (128, 75, 10, 'Hyatt-Kuhn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (129, 8, 80, 'Ritchie, Bayer and Larson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (130, 94, 11, 'Beatty, Bogisich and Olson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (131, 90, 98, 'Kiehn and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (132, 73, 61, 'Hagenes, Grimes and Green');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (133, 74, 65, 'Welch, Heaney and Wunsch');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (134, 39, 39, 'Bode Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (135, 42, 88, 'O''Conner, Pacocha and Gerlach');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (136, 61, 7, 'Carroll LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (137, 99, 68, 'Bogan-Morar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (138, 57, 97, 'Swift, Rohan and Lang');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (139, 69, 95, 'Cruickshank Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (140, 100, 86, 'Effertz and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (141, 15, 100, 'Stehr-Kilback');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (142, 15, 59, 'Keeling, Connelly and Schuster');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (143, 29, 53, 'Price-Kemmer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (144, 47, 90, 'Fritsch Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (145, 10, 100, 'Lind, Johnston and O''Keefe');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (146, 68, 90, 'Beahan-Kilback');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (147, 40, 1, 'Wolf-Haag');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (148, 2, 12, 'Bechtelar and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (149, 74, 87, 'Bartell Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (150, 89, 44, 'Stark LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (151, 9, 47, 'Rath-Upton');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (152, 80, 94, 'Jakubowski, Kunze and Robel');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (153, 90, 51, 'Waelchi Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (154, 11, 2, 'Moen-Mohr');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (155, 41, 78, 'Erdman-Collier');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (156, 38, 28, 'Langosh, Nicolas and Kshlerin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (157, 9, 71, 'Hane-Bednar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (158, 57, 91, 'Bins, Herzog and Waelchi');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (159, 36, 26, 'Lakin, Lebsack and Zulauf');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (160, 83, 17, 'Cummings-Balistreri');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (161, 86, 80, 'Witting-Schuster');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (162, 58, 100, 'Conroy, Bosco and Altenwerth');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (163, 61, 61, 'Kreiger-Gorczany');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (164, 22, 64, 'Jast, Hartmann and Becker');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (165, 42, 96, 'Mitchell, Legros and Johnson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (166, 41, 95, 'Cole, Lowe and Walsh');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (167, 53, 73, 'Reichel, Romaguera and Bednar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (168, 29, 11, 'Davis-Lehner');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (169, 78, 86, 'Schulist, Kuhic and Lowe');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (170, 40, 95, 'Hartmann-Grimes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (171, 25, 55, 'Connelly-Mante');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (172, 28, 41, 'Gutmann-Rohan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (173, 91, 28, 'Wilderman, Dare and Schiller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (174, 74, 99, 'Aufderhar-Auer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (175, 80, 43, 'Leffler-Friesen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (176, 11, 55, 'Gaylord Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (177, 77, 47, 'Sawayn Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (178, 28, 41, 'Spinka-Collins');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (179, 6, 64, 'Rutherford LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (180, 7, 22, 'Stamm-Jacobson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (181, 87, 39, 'Watsica, Abbott and Hilll');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (182, 15, 56, 'Wolff-Windler');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (183, 89, 57, 'Feil-Okuneva');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (184, 38, 1, 'Smith-McKenzie');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (185, 11, 62, 'Schaden, Kutch and Nienow');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (186, 1, 32, 'Abbott Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (187, 18, 2, 'Torp-Schmeler');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (188, 39, 90, 'Bogisich Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (189, 55, 44, 'Wiegand-Feil');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (190, 57, 12, 'DuBuque, Kohler and Hickle');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (191, 100, 74, 'Rempel-Dietrich');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (192, 24, 68, 'Veum-Williamson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (193, 39, 87, 'Zboncak-Stroman');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (194, 73, 49, 'Leuschke LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (195, 81, 11, 'Bergnaum Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (196, 15, 94, 'Hoeger, Tillman and Marks');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (197, 93, 50, 'Boyer-Lubowitz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (198, 42, 86, 'Bernier LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (199, 71, 79, 'Ward, Kertzmann and Reynolds');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (200, 27, 49, 'Bauch and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (201, 99, 59, 'Heathcote Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (202, 64, 20, 'Boyer-Green');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (203, 74, 16, 'Hegmann, Stehr and Heller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (204, 96, 50, 'Wolff-Jakubowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (205, 70, 70, 'Osinski, Smitham and Schinner');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (206, 9, 73, 'Legros and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (207, 91, 23, 'Bernier Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (208, 51, 69, 'Windler-Reilly');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (209, 58, 21, 'Altenwerth-Ankunding');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (210, 34, 82, 'Corkery, Sipes and Davis');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (211, 100, 51, 'Tromp Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (212, 9, 14, 'Huel Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (213, 87, 58, 'Fahey, Treutel and VonRueden');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (214, 31, 9, 'Harris, Schneider and Haag');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (215, 12, 99, 'Schneider-Bechtelar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (216, 83, 66, 'Little, Orn and Grimes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (217, 55, 45, 'Miller-Altenwerth');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (218, 2, 35, 'Emard-Cummings');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (219, 34, 43, 'Hermann, Koch and Pfeffer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (220, 36, 43, 'Powlowski-Bashirian');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (221, 9, 65, 'Legros, Jenkins and Raynor');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (222, 8, 92, 'Will-Mann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (223, 87, 97, 'Bins, Wilkinson and Larson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (224, 15, 7, 'Cassin Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (225, 36, 38, 'Leffler-Dietrich');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (226, 23, 97, 'Osinski-Hegmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (227, 29, 19, 'Zboncak Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (228, 62, 47, 'Graham and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (229, 49, 98, 'Ratke and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (230, 27, 56, 'Gibson-Hodkiewicz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (231, 93, 94, 'Johnston-Marvin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (232, 11, 37, 'Orn Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (233, 7, 51, 'Ziemann, Lebsack and Shanahan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (234, 84, 96, 'Anderson-Monahan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (235, 79, 41, 'Wyman-Gorczany');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (236, 70, 95, 'Huel-Bernhard');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (237, 23, 67, 'Goyette Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (238, 3, 48, 'Olson, Ebert and Koepp');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (239, 10, 41, 'Hintz, Hauck and Stanton');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (240, 86, 53, 'Stanton-Eichmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (241, 54, 29, 'Jaskolski-Wehner');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (242, 46, 12, 'Reinger-Stokes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (243, 18, 18, 'Ruecker, Pfannerstill and Towne');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (244, 21, 32, 'Bergnaum, Casper and Denesik');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (245, 66, 86, 'Reichel, Metz and Prosacco');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (246, 85, 93, 'Nolan and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (247, 42, 22, 'Nader-Steuber');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (248, 59, 68, 'Pollich Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (249, 7, 99, 'Moen, Johnston and Fadel');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (250, 42, 13, 'Auer Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (251, 68, 68, 'Block, Schmitt and Conn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (252, 30, 41, 'Pagac and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (253, 35, 38, 'Connelly-Metz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (254, 19, 76, 'Abbott-Eichmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (255, 71, 99, 'Emard LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (256, 13, 53, 'Moore, Howe and Moore');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (257, 5, 87, 'Kuhlman Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (258, 60, 51, 'Volkman-Wunsch');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (259, 76, 62, 'Altenwerth, Haley and Harris');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (260, 49, 67, 'Bailey, Moore and Lueilwitz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (261, 49, 11, 'Hand-Hayes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (262, 28, 75, 'Stracke, Harber and Nicolas');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (263, 89, 4, 'O''Hara-Weissnat');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (264, 43, 39, 'Rath-Lubowitz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (265, 59, 99, 'Hintz-Bruen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (266, 96, 23, 'Bauch Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (267, 31, 62, 'Flatley LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (268, 54, 43, 'Bogisich LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (269, 82, 41, 'Torphy, Torphy and Rutherford');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (270, 5, 94, 'Mohr-Cruickshank');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (271, 83, 40, 'Cole-Kuhn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (272, 78, 87, 'Sawayn, Walsh and Rempel');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (273, 25, 50, 'Kris-Schmitt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (274, 48, 34, 'Hintz, Feeney and VonRueden');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (275, 8, 70, 'Metz-Gerhold');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (276, 53, 80, 'Morar Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (277, 24, 59, 'Von, Stokes and Lockman');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (278, 71, 83, 'McKenzie Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (279, 97, 18, 'Ankunding-Waters');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (280, 42, 38, 'Heidenreich-Gusikowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (281, 8, 26, 'Corkery-Jakubowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (282, 77, 54, 'Anderson LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (283, 11, 89, 'Goldner-Daugherty');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (284, 96, 38, 'Bergstrom Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (285, 94, 22, 'Reichert Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (286, 22, 50, 'Bosco-Waters');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (287, 22, 16, 'Brown-Hilll');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (288, 31, 88, 'Donnelly, Bashirian and Larkin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (289, 15, 69, 'Altenwerth-Kovacek');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (290, 68, 93, 'Lynch LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (291, 75, 92, 'Kihn Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (292, 38, 21, 'Bergnaum, Ankunding and Jacobs');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (293, 49, 70, 'Ernser, Frami and Nader');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (294, 3, 53, 'Ledner-Heller');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (295, 79, 66, 'Ankunding-Weimann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (296, 20, 27, 'Nolan-Durgan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (297, 44, 43, 'O''Hara LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (298, 18, 83, 'Olson Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (299, 24, 13, 'Eichmann-Langosh');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (300, 86, 92, 'Cartwright and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (301, 21, 16, 'Dach-Rowe');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (302, 7, 78, 'O''Connell-Dickinson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (303, 26, 24, 'Bradtke, Mitchell and Carter');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (304, 16, 5, 'Gottlieb LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (305, 28, 44, 'Lynch, Nader and Smitham');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (306, 31, 18, 'Waters Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (307, 23, 4, 'Orn LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (308, 38, 48, 'Padberg, Kohler and Wisoky');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (309, 59, 66, 'Mohr Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (310, 20, 95, 'Moen, Kerluke and Torp');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (311, 48, 80, 'Dicki-Hilll');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (312, 71, 24, 'Purdy-Aufderhar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (313, 26, 14, 'Corkery LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (314, 12, 17, 'Yost-Bergstrom');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (315, 51, 32, 'Deckow, Anderson and Kovacek');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (316, 51, 2, 'Ryan Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (317, 30, 21, 'Stiedemann, Gibson and Roob');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (318, 62, 28, 'Rohan Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (319, 1, 63, 'Dooley-Borer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (320, 96, 80, 'Kirlin, Kub and Koepp');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (321, 41, 26, 'Kutch-Wuckert');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (322, 57, 41, 'Quitzon-Kreiger');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (323, 10, 67, 'Little Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (324, 64, 22, 'Flatley-Ortiz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (325, 23, 92, 'Weimann and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (326, 75, 94, 'Streich Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (327, 6, 99, 'Kutch, Bernier and Larson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (328, 65, 33, 'Vandervort, Zboncak and Bergnaum');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (329, 15, 98, 'Anderson, Block and Murphy');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (330, 4, 8, 'Grimes, Homenick and Pagac');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (331, 14, 71, 'Crooks, Trantow and Ward');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (332, 50, 49, 'Johns-Legros');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (333, 76, 50, 'Padberg, Swaniawski and Kiehn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (334, 56, 75, 'Johns-Cronin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (335, 82, 82, 'Effertz-Walsh');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (336, 27, 42, 'Romaguera-Pfannerstill');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (337, 91, 79, 'Littel-Shanahan');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (338, 68, 65, 'Dibbert Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (339, 100, 23, 'Cassin-Lakin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (340, 43, 93, 'Paucek Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (341, 78, 70, 'Gleason-Ebert');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (342, 65, 71, 'Beer-Aufderhar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (343, 86, 61, 'Gibson-Bosco');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (344, 58, 1, 'Rowe, Stanton and Kirlin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (345, 30, 5, 'Rodriguez-Hermiston');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (346, 60, 35, 'Lynch-Gibson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (347, 33, 12, 'Auer Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (348, 95, 94, 'Blanda and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (349, 67, 8, 'Spinka-Powlowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (350, 67, 78, 'Armstrong-Veum');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (351, 71, 37, 'Graham-Bartoletti');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (352, 16, 36, 'Donnelly Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (353, 68, 50, 'Toy LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (354, 62, 5, 'Ratke, Goyette and Wisoky');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (355, 84, 14, 'Braun-Marquardt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (356, 43, 66, 'Cummerata LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (357, 44, 99, 'Hirthe Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (358, 53, 6, 'O''Connell, Robel and Kuphal');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (359, 10, 57, 'Nienow Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (360, 69, 44, 'Stamm-Feeney');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (361, 26, 24, 'Roberts and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (362, 13, 9, 'Robel-Gutmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (363, 96, 38, 'Gorczany, Kessler and Kihn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (364, 42, 33, 'Tromp Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (365, 67, 87, 'Lynch, Harris and Reilly');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (366, 48, 65, 'Williamson-Witting');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (367, 21, 10, 'Schuppe-Wolf');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (368, 13, 97, 'Carroll, Borer and Schaden');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (369, 46, 58, 'Hirthe LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (370, 80, 48, 'Beatty, Pouros and Cummings');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (371, 8, 2, 'Cormier-McGlynn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (372, 54, 50, 'Veum LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (373, 71, 84, 'Schuppe-Turcotte');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (374, 68, 16, 'Wilderman, Bradtke and Hilll');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (375, 89, 81, 'Lebsack LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (376, 26, 20, 'Mills-Schmidt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (377, 85, 32, 'DuBuque and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (378, 13, 22, 'Cormier, Boehm and Harvey');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (379, 85, 99, 'Jacobi Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (380, 93, 74, 'Tromp Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (381, 96, 82, 'Stiedemann, Altenwerth and Wuckert');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (382, 24, 40, 'Hoeger and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (383, 60, 74, 'Wolff Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (384, 32, 71, 'Hermann-Schoen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (385, 77, 7, 'Koss-Raynor');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (386, 7, 76, 'DuBuque-Kunde');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (387, 26, 73, 'Heaney, Spinka and Hammes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (388, 12, 6, 'Erdman-Fay');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (389, 2, 24, 'Grant, Mayert and Dibbert');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (390, 40, 31, 'Robel-Stark');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (391, 68, 71, 'Harvey, Beer and Jacobi');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (392, 84, 57, 'Beahan-Conroy');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (393, 64, 98, 'Botsford, Sporer and Leffler');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (394, 22, 28, 'Fritsch-Reilly');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (395, 85, 64, 'Turcotte-Bechtelar');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (396, 81, 46, 'Toy-Orn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (397, 58, 35, 'Muller Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (398, 16, 8, 'Carter LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (399, 9, 25, 'Labadie-Koepp');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (400, 31, 55, 'Turner, Funk and Wintheiser');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (401, 19, 56, 'Crona, Stark and Metz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (402, 57, 89, 'Stamm Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (403, 41, 79, 'Nitzsche and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (404, 84, 80, 'Rempel, Langosh and Lueilwitz');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (405, 62, 5, 'Abshire, Cole and Dickinson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (406, 75, 30, 'Dickinson LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (407, 50, 17, 'Brekke Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (408, 56, 53, 'Pagac-Rowe');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (409, 45, 14, 'Yost-Bode');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (410, 17, 83, 'Lueilwitz Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (411, 9, 54, 'Hettinger-Koss');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (412, 82, 62, 'Cremin, Klein and Wisoky');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (413, 96, 88, 'Torphy-Mann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (414, 8, 81, 'Schinner, Rutherford and Kreiger');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (415, 82, 60, 'Tremblay-Cruickshank');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (416, 93, 1, 'Fadel-Hyatt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (417, 27, 10, 'Leffler, Kemmer and Feest');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (418, 15, 58, 'Harber LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (419, 17, 95, 'Goodwin and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (420, 62, 88, 'Haley Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (421, 13, 77, 'Watsica-Bergnaum');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (422, 91, 76, 'Lang Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (423, 6, 39, 'Murray and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (424, 95, 49, 'Kuphal Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (425, 80, 63, 'Koepp-Conn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (426, 57, 3, 'Schaefer, Bosco and Waters');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (427, 61, 42, 'Gibson LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (428, 13, 48, 'Windler-Halvorson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (429, 20, 3, 'Klocko and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (430, 34, 15, 'Rohan, Kemmer and Bergnaum');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (431, 48, 95, 'Hand, Crona and Kovacek');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (432, 3, 59, 'Leuschke-Barton');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (433, 32, 24, 'Langworth, Daniel and Volkman');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (434, 58, 24, 'Haag, Schiller and Moen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (435, 25, 27, 'Hane and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (436, 79, 65, 'D''Amore-Price');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (437, 69, 6, 'Kirlin Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (438, 96, 9, 'Predovic-Koelpin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (439, 73, 16, 'VonRueden-Zemlak');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (440, 7, 14, 'Corkery, Cummings and Gulgowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (441, 34, 68, 'Lemke-Wunsch');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (442, 23, 19, 'Gottlieb, Murazik and Bailey');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (443, 23, 16, 'Robel LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (444, 95, 68, 'Greenholt-Wisoky');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (445, 71, 60, 'Kshlerin and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (446, 86, 91, 'MacGyver, Hamill and Rowe');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (447, 42, 48, 'Quitzon LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (448, 2, 2, 'Kuhn, Howell and DuBuque');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (449, 49, 50, 'Pfannerstill-Herzog');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (450, 81, 8, 'Smith, Smitham and McCullough');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (451, 92, 59, 'Weissnat, Ruecker and Baumbach');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (452, 72, 66, 'Altenwerth-Hammes');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (453, 81, 90, 'Quitzon-Dach');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (454, 67, 71, 'Mueller-Jones');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (455, 97, 41, 'Hyatt, Bergnaum and Lind');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (456, 9, 38, 'Cruickshank LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (457, 60, 7, 'Harber Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (458, 48, 55, 'Towne Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (459, 35, 61, 'Schumm-Pfannerstill');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (460, 49, 98, 'Padberg and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (461, 63, 75, 'Corwin-Abbott');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (462, 59, 94, 'Carroll LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (463, 38, 32, 'Schroeder-Zulauf');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (464, 29, 10, 'Konopelski, Hirthe and Jones');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (465, 37, 92, 'Stamm-Jakubowski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (466, 20, 18, 'Kertzmann-Doyle');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (467, 83, 66, 'Harvey Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (468, 82, 38, 'Borer, Ullrich and McClure');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (469, 88, 53, 'Murazik, Purdy and Gleichner');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (470, 99, 11, 'Lemke-Stracke');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (471, 21, 58, 'Von Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (472, 42, 52, 'Schuppe Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (473, 49, 67, 'Wisozk, Hudson and Gutmann');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (474, 34, 40, 'Moen Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (475, 27, 68, 'Kuvalis-Kuhn');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (476, 75, 98, 'Hyatt Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (477, 44, 19, 'Mertz Group');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (478, 74, 61, 'Hagenes, Carter and VonRueden');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (479, 14, 94, 'Zulauf and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (480, 18, 52, 'Robel-McDermott');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (481, 6, 72, 'Mraz and Sons');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (482, 8, 88, 'Stokes, Kuphal and Stracke');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (483, 92, 51, 'Kshlerin, Cartwright and Raynor');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (484, 83, 56, 'Adams, Morissette and Luettgen');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (485, 28, 51, 'Turcotte LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (486, 26, 5, 'Jakubowski-Fay');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (487, 36, 54, 'Welch, Leannon and Rippin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (488, 100, 66, 'Jacobi, Upton and Pfeffer');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (489, 51, 69, 'Torphy, Bailey and Barrows');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (490, 14, 48, 'Schultz, Bode and Osinski');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (491, 50, 72, 'Moore, Swift and Price');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (492, 98, 32, 'Streich, Bogisich and Williamson');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (493, 4, 52, 'Rodriguez LLC');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (494, 79, 22, 'Koss, Bednar and Champlin');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (495, 95, 94, 'Reinger, Lowe and Blick');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (496, 62, 49, 'Schaefer Inc');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (497, 55, 69, 'Pfeffer-Fay');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (498, 75, 31, 'Buckridge-Bernier');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (499, 26, 49, 'Stoltenberg, Bartell and Marquardt');
insert into batata (cosigo, pontuacao, num_rodadas, nome) values (500, 75, 2, 'Gottlieb, Jacobson and Gaylord');
