insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (1, 22, 10, 'Josi');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (2, 40, 11, 'Konstantin');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (3, 34, 16, 'Gallard');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (4, 46, 12, 'Arvy');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (5, 43, 8, 'Alexis');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (6, 26, 44, 'Lisette');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (7, 47, 78, 'Welby');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (8, 33, 65, 'Marcelo');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (9, 91, 53, 'Goddart');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (10, 35, 23, 'Earlie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (11, 90, 21, 'Sheba');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (12, 41, 11, 'Hermina');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (13, 91, 9, 'Serge');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (14, 42, 13, 'Jasper');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (15, 76, 22, 'Kellina');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (16, 71, 16, 'Phedra');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (17, 21, 14, 'Oby');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (18, 86, 17, 'Ethel');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (19, 12, 16, 'Mickey');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (20, 96, 12, 'Filippa');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (21, 29, 11, 'Lyda');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (22, 34, 15, 'Vladimir');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (23, 65, 15, 'Lydie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (24, 79, 16, 'Rene');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (25, 81, 14, 'Jeddy');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (26, 2, 15, 'Fae');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (27, 60, 16, 'Roddie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (28, 57, 15, 'Terence');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (29, 38, 14, 'Laney');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (30, 73, 15, 'Maxy');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (31, 68, 15, 'Darci');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (32, 31, 16, 'Charil');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (33, 82, 12, 'Ingunna');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (34, 59, 14,'Batata');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (35, 99,12,'Noni');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (36, 44, 15, 'Latisha');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (37, 86, 15, 'Abbe');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (38, 51, 12, 'Dara');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (39, 47, 15, 'Corrie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (40, 40, 14, 'Valma');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (41, 69, 16, 'Camella');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (42, 55, 16, 'Mendel');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (43, 12, 12, 'Terrence');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (44, 1, 12, 'Elwin');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (45, 24, 15, 'Inger');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (46, 90, 14, 'Darryl');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (47, 13, 16, 'Dasya');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (48, 16, 13, 'Beale');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (49, 32, 12, 'Jeffie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (50, 38, 15, 'Orv');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (51, 8, 15, 'Roseann');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (52, 17, 15, 'Lexine');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (53, 27, 14, 'Brockie');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (54, 43, 13, 'Wayland');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (55, 78, 12, 'Lauralee');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (56, 85, 12, 'Isac');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (57, 65, 12, 'Alejandra');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (58, 81, 14, 'Boy');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (59, 67, 17, 'Beret');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (60, 48, 12, 'Kristy');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (61, 2, 13, 'Lazar');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (62, 84, 12, 'Sal');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (63, 30, 13, 'Charo');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (64, 37, 14, 'Dare');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (65, 72, 14, 'Wright');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (66, 50, 15, 'Karoly');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (67, 41, 15, 'Pablo');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (68, 15, 14, 'Legra');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (69, 8, 12, 'Borg');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (70, 29, 16, 'Althea');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (71, 10, 15, 'Ailee');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (72, 19, 14, 'Virginia');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (73, 14, 14, 'Blinni');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (74, 95, 14, 'Patricia');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (75, 46, 14, 'Berri');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (76, 99, 564, 'Mycah');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (77, 17, 16, 'Myrvyn');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (78, 50, 15, 'Gates');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (79, 43, 14, 'Barbe');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (80, 44, 15, 'Maryjane');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (81, 96, 16, 'Oberon');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (82, 1, 16, 'Denice');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (83, 95, 12, 'Linda');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (84, 63, 14, 'Yelena');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (85, 39, 16, 'Colin');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (86, 40, 15, 'Sande');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (87, 97, 15, 'Camile');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (88, 40, 14, 'Leonid');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (89, 49, 15, 'Jackson');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (90, 58, 54, 'Arni');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (91, 17, 15, 'Truda');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (92, 59, 15, 'Rice');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (93, 14, 15, 'Sena');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (94, 6, 16, 'Florella');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (95, 68, 12, 'Jade');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (96, 88, 14, 'Dredi');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (97, 63, 14, 'Esma');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (98, 16, 15, 'Joscelin');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (99, 82, 12, 'Ortensia');
insert into campeonato (codigo, pontuacao, num_rodadas, nome) values (100, 78, 12, 'Margaretta');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (1, 10, 40, 'Zboncak, Bosco and McClure');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (2, 91, 14, 'Walsh and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (3, 19, 100, 'Feeney-Schinner');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (4, 49, 33, 'Hayes-Kshlerin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (5, 77, 76, 'Von-Kovacek');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (6, 1, 80, 'Kirlin-Halvorson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (7, 32, 28, 'Goodwin-Jacobs');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (8, 43, 69, 'Lockman, Schmidt and Sanford');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (9, 40, 95, 'Hagenes Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (10, 55, 77, 'Schroeder and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (11, 85, 24, 'Marquardt Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (12, 68, 57, 'Maggio-Conroy');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (13, 7, 65, 'Ryan and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (14, 29, 59, 'Casper-Kozey');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (15, 9, 55, 'Ortiz, McKenzie and Weimann');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (16, 81, 82, 'Turcotte Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (17, 81, 24, 'Batz LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (18, 92, 85, 'Deckow and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (19, 58, 54, 'Blanda, Bartoletti and Cartwright');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (20, 64, 49, 'Dicki-Wolf');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (21, 77, 71, 'Dach-Willms');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (22, 5, 56, 'Kihn-Veum');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (23, 58, 82, 'Sanford and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (24, 52, 10, 'Kiehn, Heidenreich and Fay');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (25, 44, 75, 'Skiles Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (26, 76, 47, 'Wisozk-Krajcik');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (27, 18, 5, 'Zemlak and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (28, 88, 44, 'Berge, Klocko and D''Amore');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (29, 50, 61, 'Rice, Bogisich and Nader');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (30, 82, 63, 'Braun-Pfeffer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (31, 5, 21, 'Buckridge-Ferry');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (32, 2, 3, 'Daugherty-Hauck');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (33, 67, 43, 'Lesch LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (34, 24, 81, 'Kuvalis, Waters and Kulas');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (35, 48, 41, 'Braun and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (36, 16, 77, 'Rath, Trantow and Schamberger');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (37, 68, 38, 'Parisian-Bartoletti');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (38, 28, 68, 'Becker Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (39, 85, 94, 'Ward, Buckridge and Emard');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (40, 7, 86, 'Friesen and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (41, 65, 12, 'Legros Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (42, 30, 54, 'Harvey LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (43, 76, 1, 'VonRueden Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (44, 25, 73, 'Prohaska and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (45, 8, 77, 'Kessler, Willms and Torphy');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (46, 20, 80, 'Nikolaus-Ryan');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (47, 94, 87, 'Von-Howell');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (48, 33, 65, 'Lind LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (49, 69, 4, 'Ward Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (50, 82, 57, 'Hermiston-Lueilwitz');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (51, 61, 72, 'Jacobs, Mills and Walsh');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (52, 18, 29, 'Glover-Kuphal');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (53, 40, 40, 'Konopelski LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (54, 53, 15, 'Hayes-Abshire');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (55, 80, 23, 'Reichel-Graham');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (56, 49, 87, 'Fadel Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (57, 90, 65, 'Johns, Mosciski and Kub');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (58, 62, 88, 'Kuvalis LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (59, 51, 49, 'Hegmann LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (60, 47, 3, 'Kautzer and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (61, 96, 35, 'Parker, Denesik and Raynor');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (62, 14, 43, 'Langworth, Legros and Hettinger');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (63, 32, 35, 'Schiller and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (64, 20, 24, 'Orn, Williamson and Mitchell');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (65, 44, 99, 'Rowe-Kassulke');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (66, 75, 23, 'Bogan-Carter');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (67, 82, 54, 'Bahringer LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (68, 17, 1, 'Franecki-Langosh');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (69, 82, 8, 'Balistreri Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (70, 46, 17, 'Murray Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (71, 99, 76, 'Stracke, Wilkinson and Price');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (72, 28, 60, 'Rutherford, Morissette and Bode');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (73, 11, 20, 'Dare-Hegmann');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (74, 1, 20, 'Grady and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (75, 48, 37, 'Lind, Botsford and Conroy');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (76, 30, 96, 'Effertz and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (77, 54, 75, 'Koch-Maggio');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (78, 30, 95, 'Boyer, Huel and Dare');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (79, 31, 51, 'Adams-Gulgowski');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (80, 52, 97, 'Durgan, Kessler and Farrell');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (81, 16, 36, 'Hahn Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (82, 8, 49, 'Hartmann LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (83, 74, 36, 'Erdman-Predovic');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (84, 67, 7, 'Kautzer Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (85, 25, 20, 'West Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (86, 44, 60, 'Romaguera, Weimann and Parker');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (87, 55, 65, 'McKenzie-Mraz');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (88, 9, 98, 'Grant LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (89, 12, 56, 'Hudson Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (90, 84, 80, 'Bergstrom, Watsica and Will');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (91, 87, 19, 'Cronin Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (92, 96, 12, 'Rempel, Wyman and Wyman');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (93, 62, 49, 'Kilback, Nitzsche and Lehner');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (94, 11, 27, 'Bauch and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (95, 79, 47, 'Bailey-Littel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (96, 69, 14, 'Carter, Bernier and Osinski');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (97, 63, 74, 'Gulgowski Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (98, 95, 78, 'White, Bechtelar and Carter');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (99, 77, 11, 'Huels-Zieme');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (100, 39, 16, 'Metz, Moen and Mills');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (101, 11, 63, 'Lebsack LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (102, 76, 46, 'Cassin-Altenwerth');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (103, 37, 47, 'Dicki and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (104, 100, 5, 'Stehr Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (105, 43, 29, 'Huel LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (106, 20, 24, 'Fahey, Ruecker and Nitzsche');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (107, 21, 31, 'Grimes-Quitzon');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (108, 62, 41, 'Maggio LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (109, 50, 12, 'Gleichner Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (110, 60, 10, 'Jones and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (111, 95, 11, 'Gerhold, Kub and Jenkins');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (112, 79, 42, 'Runte Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (113, 99, 76, 'Kuhic LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (114, 24, 45, 'Hegmann-Walter');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (115, 7, 4, 'Brakus-Gleichner');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (116, 59, 56, 'Nader, Wunsch and Larson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (117, 26, 80, 'Reynolds, Dicki and Schmitt');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (118, 82, 71, 'Wunsch and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (119, 65, 97, 'Reynolds-Jerde');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (120, 91, 20, 'Koepp Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (121, 74, 55, 'Denesik, Pouros and Graham');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (122, 21, 91, 'Erdman-Cormier');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (123, 94, 82, 'Kunze-Krajcik');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (124, 95, 60, 'Gleason LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (125, 16, 68, 'Murray Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (126, 56, 91, 'Abshire LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (127, 5, 54, 'Bashirian-Raynor');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (128, 92, 85, 'Lockman-Little');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (129, 30, 62, 'Nienow-Hansen');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (130, 1, 55, 'Tromp, Monahan and Schimmel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (131, 1, 89, 'Jerde, Thiel and Carroll');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (132, 46, 7, 'Lakin, Stanton and Schowalter');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (133, 88, 49, 'Murphy, Hane and Goodwin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (134, 89, 54, 'Paucek, Jakubowski and Rau');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (135, 19, 32, 'Hudson and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (136, 53, 16, 'Toy, Howe and Grimes');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (137, 3, 13, 'Wuckert-Kemmer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (138, 2, 83, 'Homenick-Dickens');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (139, 87, 28, 'Schroeder, Stroman and Jenkins');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (140, 9, 88, 'Bode, Rippin and Fadel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (141, 13, 18, 'Sporer-Considine');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (142, 25, 3, 'Lakin LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (143, 40, 41, 'Gottlieb, Paucek and Simonis');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (144, 64, 93, 'Parisian, Okuneva and Lueilwitz');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (145, 94, 68, 'Boehm, O''Conner and Cassin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (146, 31, 95, 'Collins-Kub');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (147, 84, 93, 'Stoltenberg-Walter');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (148, 94, 77, 'Shanahan LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (149, 21, 38, 'Hermiston, Bailey and Schumm');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (150, 76, 73, 'Mills Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (151, 93, 58, 'Huel-Schoen');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (152, 63, 61, 'Beer-Kris');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (153, 99, 87, 'Ankunding, McCullough and Swift');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (154, 83, 28, 'Torp-Crona');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (155, 74, 1, 'Goldner-Boyer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (156, 87, 88, 'Lockman, Howell and Funk');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (157, 48, 48, 'Weissnat Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (158, 73, 30, 'Klein and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (159, 49, 100, 'Marvin, Eichmann and Watsica');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (160, 57, 35, 'Wilkinson, Koelpin and Murphy');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (161, 91, 73, 'Huel and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (162, 55, 92, 'Blanda and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (163, 19, 35, 'Littel and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (164, 96, 83, 'Wilderman, Corkery and Feil');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (165, 92, 81, 'Block-Simonis');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (166, 68, 65, 'Price, Mitchell and Feeney');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (167, 19, 90, 'O''Connell Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (168, 4, 15, 'Goldner-Bosco');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (169, 90, 39, 'Stoltenberg-Cassin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (170, 33, 86, 'Russel, Bogan and Stracke');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (171, 61, 36, 'Green and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (172, 26, 90, 'Smith-Gibson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (173, 60, 58, 'Zemlak, Bauch and Bechtelar');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (174, 37, 23, 'Marks and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (175, 78, 26, 'Crona-Keeling');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (176, 82, 25, 'Corkery-Smitham');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (177, 88, 58, 'Rau, Feest and Grady');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (178, 57, 25, 'Hahn, Stiedemann and Quitzon');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (179, 97, 75, 'Schimmel, Hudson and Balistreri');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (180, 13, 90, 'Langworth LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (181, 58, 76, 'Erdman-Walsh');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (182, 46, 46, 'Durgan and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (183, 20, 65, 'Gusikowski Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (184, 58, 82, 'Koss, Auer and Kihn');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (185, 37, 74, 'Beahan and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (186, 86, 27, 'Hermann LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (187, 57, 79, 'Marvin, Halvorson and Gerlach');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (188, 19, 92, 'Bins-Eichmann');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (189, 26, 87, 'Sauer and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (190, 10, 70, 'Schuppe LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (191, 25, 49, 'Swift-Larson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (192, 92, 17, 'Feest Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (193, 95, 27, 'Klocko-Kunde');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (194, 92, 54, 'Schmitt, Nader and Murray');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (195, 4, 29, 'Mohr LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (196, 13, 28, 'McKenzie-Rempel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (197, 67, 70, 'Eichmann, Jacobi and Mayert');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (198, 31, 82, 'Crona and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (199, 37, 57, 'Rau, Toy and Wiza');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (200, 97, 97, 'Douglas Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (201, 28, 29, 'Tromp LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (202, 61, 81, 'Ondricka-Price');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (203, 78, 4, 'Heaney and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (204, 14, 18, 'West, Murray and McLaughlin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (205, 60, 25, 'Haag Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (206, 17, 10, 'Paucek-Lakin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (207, 44, 39, 'Bernhard-Ward');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (208, 26, 96, 'Cole LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (209, 23, 18, 'Schuster Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (210, 49, 74, 'Bogisich Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (211, 38, 3, 'Cronin and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (212, 75, 6, 'Bogisich Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (213, 22, 76, 'Corwin, Howell and Hauck');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (214, 16, 4, 'Krajcik and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (215, 78, 59, 'Sporer-Wiza');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (216, 63, 46, 'Kuphal Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (217, 96, 61, 'Schmitt-Kuphal');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (218, 92, 59, 'Turner-Von');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (219, 81, 11, 'Homenick-Pfannerstill');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (220, 67, 66, 'McGlynn Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (221, 95, 65, 'Becker, Yost and Jones');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (222, 75, 61, 'O''Hara LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (223, 64, 5, 'Hyatt Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (224, 65, 41, 'Boyer-Cole');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (225, 72, 24, 'Spinka Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (226, 74, 42, 'Conn Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (227, 77, 89, 'Kiehn Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (228, 91, 68, 'Smith-Zieme');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (229, 15, 94, 'Schmidt-Pagac');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (230, 14, 24, 'Hoeger-Schamberger');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (231, 38, 45, 'Beer-Marvin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (232, 90, 75, 'Okuneva, Konopelski and Jacobson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (233, 51, 49, 'Connelly-Erdman');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (234, 64, 95, 'Roberts, Bode and Goldner');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (235, 75, 40, 'Keebler Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (236, 17, 54, 'Koelpin-Stamm');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (237, 49, 85, 'Deckow and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (238, 23, 91, 'Davis Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (239, 66, 76, 'Ernser-Greenfelder');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (240, 21, 69, 'Bednar-Beier');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (241, 18, 100, 'Rice-Schiller');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (242, 29, 17, 'Gislason-McLaughlin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (243, 44, 34, 'Marvin, Dickinson and West');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (244, 99, 50, 'Oberbrunner, Schulist and Kemmer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (245, 5, 14, 'Shanahan, Grant and O''Keefe');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (246, 89, 85, 'Hodkiewicz, Dickinson and Grady');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (247, 68, 68, 'Konopelski, Kling and Bruen');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (248, 42, 67, 'Koepp, Bruen and Daugherty');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (249, 63, 28, 'Heller Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (250, 31, 12, 'Rice Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (251, 20, 100, 'Kuhn, Krajcik and Gleichner');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (252, 50, 6, 'Goyette-Flatley');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (253, 90, 93, 'Barton LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (254, 43, 32, 'Kunze-Tromp');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (255, 19, 6, 'Welch-Mayert');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (256, 14, 95, 'Gerlach, Hermann and Bauch');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (257, 8, 77, 'Oberbrunner Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (258, 11, 13, 'Dickinson, Satterfield and Lesch');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (259, 43, 13, 'Labadie LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (260, 48, 30, 'Bradtke Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (261, 78, 24, 'Ruecker Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (262, 52, 28, 'Beer-Walker');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (263, 50, 51, 'Hoeger-Mohr');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (264, 10, 70, 'Reinger-Emmerich');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (265, 62, 62, 'Flatley, Treutel and Cole');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (266, 69, 21, 'Stiedemann Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (267, 75, 85, 'Bradtke-Bradtke');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (268, 96, 33, 'Romaguera-Kirlin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (269, 55, 37, 'Wehner and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (270, 30, 9, 'Parisian and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (271, 37, 61, 'Strosin, Johnston and Osinski');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (272, 64, 17, 'Bartoletti Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (273, 81, 2, 'Mosciski and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (274, 6, 92, 'Schuster, Krajcik and Quigley');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (275, 76, 90, 'Cummings Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (276, 62, 93, 'Nicolas and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (277, 51, 46, 'Jacobson Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (278, 70, 32, 'Casper LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (279, 20, 51, 'Batz Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (280, 40, 54, 'Kirlin-Lebsack');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (281, 85, 98, 'Upton Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (282, 3, 35, 'McKenzie-Kuvalis');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (283, 65, 64, 'Hills-Koepp');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (284, 10, 47, 'Greenholt-Bergstrom');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (285, 10, 52, 'Ferry Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (286, 87, 69, 'Rutherford, Harvey and Olson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (287, 25, 40, 'Bins LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (288, 27, 57, 'Nitzsche-Brekke');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (289, 56, 44, 'Marks-Mohr');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (290, 100, 22, 'Emard-Schultz');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (291, 39, 54, 'Buckridge, Ratke and Cartwright');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (292, 69, 36, 'Reichert, Kertzmann and McLaughlin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (293, 35, 42, 'Harber-Schuppe');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (294, 79, 63, 'Klein-Schuster');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (295, 94, 53, 'Price-Braun');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (296, 56, 82, 'Crist LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (297, 57, 54, 'Metz, Osinski and Smith');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (298, 99, 67, 'Christiansen-Douglas');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (299, 91, 3, 'Runolfsson-Dickinson');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (300, 83, 11, 'Rath-Watsica');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (301, 42, 79, 'Medhurst Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (302, 80, 35, 'Bogisich, Schmitt and Lockman');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (303, 95, 5, 'Batz, Cremin and Leannon');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (304, 14, 10, 'O''Connell and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (305, 70, 4, 'Runolfsson, Ruecker and Corwin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (306, 91, 89, 'Satterfield-Stamm');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (307, 12, 100, 'Kuhic, Durgan and Rutherford');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (308, 24, 66, 'MacGyver Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (309, 86, 38, 'Goodwin-Marks');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (310, 24, 38, 'Fadel and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (311, 90, 65, 'Corwin-Rutherford');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (312, 10, 51, 'McClure, Kerluke and Bartell');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (313, 64, 91, 'Grant and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (314, 72, 49, 'Ankunding Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (315, 83, 1, 'Bernhard-Little');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (316, 47, 97, 'Rau-Kautzer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (317, 20, 69, 'Rippin and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (318, 32, 66, 'Morar Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (319, 86, 5, 'Price-Jones');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (320, 20, 1, 'Brakus Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (321, 20, 79, 'Prohaska-Hauck');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (322, 38, 9, 'Morar, Dickinson and Strosin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (323, 57, 88, 'Kovacek, Bashirian and Becker');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (324, 36, 91, 'Fisher, Fay and Kohler');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (325, 76, 31, 'Prosacco, Gleason and Koepp');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (326, 46, 41, 'Mayert, Jacobi and Beier');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (327, 80, 56, 'Gutkowski Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (328, 98, 79, 'Heathcote-Beier');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (329, 60, 41, 'Jast Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (330, 52, 67, 'Kautzer Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (331, 38, 18, 'Hammes Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (332, 45, 37, 'Hartmann-Mosciski');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (333, 86, 17, 'Wehner Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (334, 38, 43, 'Quigley, Altenwerth and McClure');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (335, 11, 18, 'Fay, Gislason and Wiegand');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (336, 22, 42, 'Kassulke, Lind and Skiles');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (337, 70, 74, 'Harris Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (338, 51, 80, 'Schmeler-Cremin');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (339, 88, 46, 'Kunze, Price and Erdman');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (340, 56, 83, 'Anderson-Greenholt');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (341, 56, 2, 'Howe-Muller');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (342, 53, 76, 'Torp Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (343, 96, 20, 'Kuvalis LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (344, 85, 99, 'Legros, Johns and Gusikowski');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (345, 67, 31, 'Cruickshank Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (346, 85, 97, 'Dietrich, Batz and Balistreri');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (347, 76, 36, 'Roob-Brown');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (348, 16, 59, 'Thompson, Gottlieb and Gorczany');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (349, 91, 21, 'Rowe Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (350, 35, 93, 'Kessler, Morar and Runolfsdottir');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (351, 26, 95, 'Kohler-Shields');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (352, 12, 38, 'Harvey, Rau and Armstrong');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (353, 6, 67, 'Luettgen-Jenkins');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (354, 83, 100, 'Wilkinson, Turcotte and Maggio');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (355, 14, 45, 'Abbott-Roberts');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (356, 99, 21, 'Willms, Schaefer and Johns');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (357, 57, 72, 'Hermiston-Koepp');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (358, 2, 38, 'Bauch, Sporer and Spinka');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (359, 77, 54, 'Denesik Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (360, 57, 48, 'Frami-Mann');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (361, 58, 56, 'Zulauf-Morissette');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (362, 4, 9, 'Fritsch Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (363, 62, 6, 'McLaughlin, Lockman and Wilderman');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (364, 67, 6, 'Kerluke-Durgan');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (365, 86, 16, 'Donnelly LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (366, 67, 52, 'Von Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (367, 2, 26, 'Spinka, Hudson and Considine');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (368, 37, 38, 'Mills, Schiller and Torp');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (369, 82, 82, 'Wisozk-Purdy');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (370, 5, 16, 'Sauer and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (371, 98, 78, 'Friesen, Haag and Crooks');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (372, 56, 13, 'Schaefer, Ernser and Cummings');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (373, 90, 18, 'Heidenreich-Bosco');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (374, 26, 55, 'Block Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (375, 21, 17, 'Raynor-Schuppe');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (376, 19, 72, 'Hirthe, Dach and Altenwerth');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (377, 61, 6, 'Hudson Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (378, 10, 66, 'Hartmann-Treutel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (379, 92, 100, 'Stamm Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (380, 45, 3, 'Romaguera and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (381, 18, 55, 'Effertz-Rempel');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (382, 77, 14, 'Nikolaus Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (383, 6, 6, 'Mills and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (384, 53, 86, 'Upton and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (385, 88, 95, 'Heathcote-Bahringer');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (386, 52, 86, 'Fay-Dare');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (387, 88, 75, 'Schumm-Kertzmann');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (388, 18, 62, 'Zboncak-Beahan');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (389, 100, 35, 'King and Sons');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (390, 99, 86, 'Wisoky Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (391, 64, 96, 'Quitzon Group');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (392, 59, 59, 'Bashirian Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (393, 25, 24, 'Corwin Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (394, 71, 8, 'Leannon, Klocko and Reynolds');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (395, 42, 54, 'Heller, Orn and Crist');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (396, 31, 1, 'Homenick LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (397, 24, 13, 'Will LLC');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (398, 4, 24, 'Braun Inc');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (399, 85, 23, 'Beatty, Larson and Walsh');
insert into campeonato  (codigo, pontuacao, num_rodadas, nome) values (400, 13, 68, 'Gutmann-Skiles');
