insert into times (codigo, nome, cod_campeonato, num_jogadores) values (1, 'Mante-Johnston', '1', 76);
insert into times (codigo, nome, campeonato, num_jogadores) values (2, 'Langworth, Von and Harvey', '1', 91);
insert into times (codigo, nome, campeonato, num_jogadores) values (3, 'Langworth-Konopelski', '1', 54);
insert into times (codigo, nome, campeonato, num_jogadores) values (4, 'Lynch LLC', '1', 64);
insert into times (codigo, nome, campeonato, num_jogadores) values (5, 'Lubowitz-Friesen', '1', 62);
insert into times (codigo, nome, campeonato, num_jogadores) values (6, 'Bahringer and Sons', '2', 15);
insert into times (codigo, nome, campeonato, num_jogadores) values (7, 'Moen LLC', '2', 20);
insert into times (codigo, nome, campeonato, num_jogadores) values (8, 'Harris Inc', '3', 64);
insert into times (codigo, nome, campeonato, num_jogadores) values (9, 'O''Connell Group', '2', 58);
insert into times (codigo, nome, campeonato, num_jogadores) values (10, 'Kling and Sons', '1', 38);
insert into times (codigo, nome, campeonato, num_jogadores) values (11, 'Hilpert, Krajcik and Hamill', '2', 61);
insert into times (codigo, nome, campeonato, num_jogadores) values (12, 'Kautzer, Corkery and Lebsack', '3', 63);
insert into times (codigo, nome, campeonato, num_jogadores) values (13, 'Balistreri, Abbott and Brakus', '2', 83);
insert into times (codigo, nome, campeonato, num_jogadores) values (14, 'Ullrich, Braun and Schmitt', '2', 53);
insert into times (codigo, nome, campeonato, num_jogadores) values (15, 'Jerde, Senger and Renner', '2', 66);
insert into times (codigo, nome, campeonato, num_jogadores) values (16, 'Rice, Kozey and Stark', '4', 32);
insert into times (codigo, nome, campeonato, num_jogadores) values (17, 'Morissette-Kassulke', '5', 27);
insert into times (codigo, nome, campeonato, num_jogadores) values (18, 'Schroeder and Sons', '5', 42);
insert into times (codigo, nome, campeonato, num_jogadores) values (19, 'Pfannerstill Inc', '9', 27);
insert into times (codigo, nome, campeonato, num_jogadores) values (20, 'Champlin, Kessler and Schroeder', '3', 99);
insert into times (codigo, nome, campeonato, num_jogadores) values (21, 'Lockman-Wiegand', '8', 68);
insert into times (codigo, nome, campeonato, num_jogadores) values (22, 'Rau-Rogahn', '3', 3);
insert into times (codigo, nome, campeonato, num_jogadores) values (23, 'Ferry Inc', '6', 84);
insert into times (codigo, nome, campeonato, num_jogadores) values (24, 'Pollich-Collins', '2', 24);
insert into times (codigo, nome, campeonato, num_jogadores) values (25, 'Kub-Eichmann', '4', 53);
insert into times (codigo, nome, campeonato, num_jogadores) values (26, 'Pacocha-Wehner', '3', 21);
insert into times (codigo, nome, campeonato, num_jogadores) values (27, 'Cruickshank-Wiza', '2', 89);
insert into times (codigo, nome, campeonato, num_jogadores) values (28, 'Davis and Sons', '5', 12);
insert into times (codigo, nome, campeonato, num_jogadores) values (29, 'Cummerata-Wolf', '9', 86);
insert into times (codigo, nome, campeonato, num_jogadores) values (30, 'Berge, Durgan and O''Keefe', '3', 32);
insert into times (codigo, nome, campeonato, num_jogadores) values (31, 'Cremin and Sons', '6', 37);
insert into times (codigo, nome, campeonato, num_jogadores) values (32, 'Terry, Murazik and Strosin', '2', 64);
insert into times (codigo, nome, campeonato, num_jogadores) values (33, 'Mills Inc', '1', 96);
insert into times (codigo, nome, campeonato, num_jogadores) values (34, 'Rippin and Sons', '2', 55);
insert into times (codigo, nome, campeonato, num_jogadores) values (35, 'MacGyver-Kreiger', '2', 55);
insert into times (codigo, nome, campeonato, num_jogadores) values (36, 'Hansen, Fahey and Bartell', '2', 17);
insert into times (codigo, nome, campeonato, num_jogadores) values (37, 'Greenholt LLC', '6', 49);
insert into times (codigo, nome, campeonato, num_jogadores) values (38, 'Heathcote Inc', '2', 24);
insert into times (codigo, nome, campeonato, num_jogadores) values (39, 'Haag, Leuschke and MacGyver', '7', 4);
insert into times (codigo, nome, campeonato, num_jogadores) values (40, 'Jenkins-Koss', '7', 16);
insert into times (codigo, nome, campeonato, num_jogadores) values (41, 'Lebsack, Morissette and Bogisich', '2', 60);
insert into times (codigo, nome, campeonato, num_jogadores) values (42, 'Gislason-Torp', '5', 36);
insert into times (codigo, nome, campeonato, num_jogadores) values (43, 'Prosacco-Lowe', '5', 50);
insert into times (codigo, nome, campeonato, num_jogadores) values (44, 'Gislason-Corkery', '2', 25);
insert into times (codigo, nome, campeonato, num_jogadores) values (45, 'Dooley-Rodriguez', '2', 90);
insert into times (codigo, nome, campeonato, num_jogadores) values (46, 'Heaney, Mills and Mann', '7', 26);
insert into times (codigo, nome, campeonato, num_jogadores) values (47, 'Romaguera, Olson and Swift', '2', 29);
insert into times (codigo, nome, campeonato, num_jogadores) values (48, 'Pfannerstill Inc', '9', 62);
insert into times (codigo, nome, campeonato, num_jogadores) values (49, 'Sanford, Wintheiser and Luettgen', '5', 90);
insert into times (codigo, nome, campeonato, num_jogadores) values (50, 'Schowalter LLC', '2', 85);
insert into times (codigo, nome, campeonato, num_jogadores) values (51, 'Anderson Inc', '6', 53);
insert into times (codigo, nome, campeonato, num_jogadores) values (52, 'Larson Inc', '3', 58);
insert into times (codigo, nome, campeonato, num_jogadores) values (53, 'Bailey, Schiller and Dach', '2', 75);
insert into times (codigo, nome, campeonato, num_jogadores) values (54, 'Lubowitz-Borer', '9', 64);
insert into times (codigo, nome, campeonato, num_jogadores) values (55, 'Graham, Gibson and Sporer', '7', 88);
insert into times (codigo, nome, campeonato, num_jogadores) values (56, 'Franecki, O''Reilly and MacGyver', '9', 27);
insert into times (codigo, nome, campeonato, num_jogadores) values (57, 'Jacobi, Williamson and Torp', '5', 66);
insert into times (codigo, nome, campeonato, num_jogadores) values (58, 'Robel-Morar', '2', 98);
insert into times (codigo, nome, campeonato, num_jogadores) values (59, 'Franecki, Nolan and Simonis', '2', 90);
insert into times (codigo, nome, campeonato, num_jogadores) values (60, 'McDermott-Paucek', '8', 64);
insert into times (codigo, nome, campeonato, num_jogadores) values (61, 'Rau, Breitenberg and Leffler', '10', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (62, 'Trantow, Roberts and Cremin', '10', 31);
insert into times (codigo, nome, campeonato, num_jogadores) values (63, 'McClure-Schmeler', '10', 55);
insert into times (codigo, nome, campeonato, num_jogadores) values (64, 'Goldner and Sons', '10', 36);
insert into times (codigo, nome, campeonato, num_jogadores) values (65, 'Mann-Funk', '10', 47);
insert into times (codigo, nome, campeonato, num_jogadores) values (66, 'Rogahn-Brakus', '10', 75);
insert into times (codigo, nome, campeonato, num_jogadores) values (67, 'Skiles, Volkman and Bayer', '10', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (68, 'Maggio, Harris and Tromp', '10', 78);
insert into times (codigo, nome, campeonato, num_jogadores) values (69, 'Corinthians', '10', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (70, 'S. Paulo', '10', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (71, 'Palmeiras', '8', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (72, 'Santos', '8', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (73, 'Portuguesa', '2', 2);
insert into times (codigo, nome, campeonato, num_jogadores) values (74, 'LOusa fc', '8', 28);
insert into times (codigo, nome, campeonato, num_jogadores) values (75, 'flamengo', '2', 26);
insert into times (codigo, nome, campeonato, num_jogadores) values (76, 'botafogo', '8', 21);
insert into times (codigo, nome, campeonato, num_jogadores) values (77, 'fluminense', '10', 12);
insert into times (codigo, nome, campeonato, num_jogadores) values (78, 'vasco', '10', 23);
insert into times (codigo, nome, campeonato, num_jogadores) values (79, 'atlético pr', '9', 28);
insert into times (codigo, nome, campeonato, num_jogadores) values (80, 'atlético goianiense', '6', 26);
insert into times (codigo, nome, campeonato, num_jogadores) values (81, 'atléico paranaense', '6', 27);
insert into times (codigo, nome, campeonato, num_jogadores) values (82, 'atlético mineiro', '7', 39);
insert into times (codigo, nome, campeonato, num_jogadores) values (83, 'curitiba', '7', 23);
insert into times (codigo, nome, campeonato, num_jogadores) values (84, 'gremio', '5', 24);
insert into times (codigo, nome, campeonato, num_jogadores) values (85, 'paraná', '5', 25);
insert into times (codigo, nome, campeonato, num_jogadores) values (86, 'internacional', '4', 35);
insert into times (codigo, nome, campeonato, num_jogadores) values (87, 'river plate', '4', 21);
insert into times (codigo, nome, campeonato, num_jogadores) values (88, 'catchau fc', '4', 25);
insert into times (codigo, nome, campeonato, num_jogadores) values (89, 'Mogi Mirim', '3', 27);
insert into times (codigo, nome, campeonato, num_jogadores) values (90, 'Guarani', '3', 25);
insert into times (codigo, nome, campeonato, num_jogadores) values (91, 'Brekke', '3', 31);
insert into times (codigo, nome, campeonato, num_jogadores) values (92, 'Corkery', '4', 29);
insert into times (codigo, nome, campeonato, num_jogadores) values (93, 'Sport', '3', 29);
insert into times (codigo, nome, campeonato, num_jogadores) values (94, 'Baeha', '7', 30);
insert into times (codigo, nome, campeonato, num_jogadores) values (95, 'Chapecoense', '5', 29);
insert into times (codigo, nome, campeonato, num_jogadores) values (96, 'Barcelona', '6', 28);
insert into times (codigo, nome, campeonato, num_jogadores) values (97, 'Real Madrid', '10', 22);
insert into times (codigo, nome, campeonato, num_jogadores) values (98, 'Milan', '9', 23);
insert into times (codigo, nome, campeonato, num_jogadores) values (99, 'Torino', '7', 24);
insert into times (codigo, nome, campeonato, num_jogadores) values (100, 'Chelsea', '10', 25);
